<?php
/**
 * Custom posts for use with this theme
 */

add_action( 'init', 'custom_post_type', 0 );
/**
 * Register Custom Post Type
 */
function custom_post_type() {
	// Register Room Custom Post Type
	$labels = array(
		'name'                  => _x( 'Rooms', 'rooms', 'am' ),
		'singular_name'         => _x( 'Room', 'room', 'am' ),
		'menu_name'             => __( 'Rooms', 'am' ),
		'name_admin_bar'        => __( 'Rooms', 'am' ),
		'archives'              => __( 'Rooms Archives', 'am' ),
		'attributes'            => __( 'Rooms Attributes', 'am' ),
		'parent_item_colon'     => __( 'Parent Rooms:', 'am' ),
		'all_items'             => __( 'All Rooms', 'am' ),
		'add_new_item'          => __( 'Add Room', 'am' ),
		'add_new'               => __( 'Add Room', 'am' ),
		'new_item'              => __( 'New Room', 'am' ),
		'edit_item'             => __( 'Edit Room', 'am' ),
		'update_item'           => __( 'Update Room', 'am' ),
		'view_item'             => __( 'View Room', 'am' ),
		'view_items'            => __( 'View Rooms', 'am' ),
		'search_items'          => __( 'Search Rooms', 'am' ),
		'not_found'             => __( 'Not found', 'am' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'am' ),
		'featured_image'        => __( 'Featured Image', 'am' ),
		'set_featured_image'    => __( 'Set featured image', 'am' ),
		'remove_featured_image' => __( 'Remove featured image', 'am' ),
		'use_featured_image'    => __( 'Use as featured image', 'am' ),
		'insert_into_item'      => __( 'Insert into Room', 'am' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Room', 'am' ),
		'items_list'            => __( 'Rooms list', 'am' ),
		'items_list_navigation' => __( 'Rooms list navigation', 'am' ),
		'filter_items_list'     => __( 'Filter Rooms list', 'am' ),
	);
	$args   = array(
		'label'               => __( 'Rooms', 'am' ),
		'description'         => __( 'Rooms post type', 'am' ),
		'labels'              => $labels,
		'supports'            => array( 'title', 'custom-fields', 'page-attributes', 'thumbnail', 'excerpt', 'editor' ),
		'hierarchical'        => true,
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_rest'        => true,
		'menu_position'       => 5,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'can_export'          => true,
		'has_archive'         => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'capability_type'     => 'post',
		'rewrite'             => array(
			'with_front' => false,
			'slug'       => 'rooms',
		),
		'menu_icon'           => 'dashicons-building',
	);
	register_post_type( 'room', $args );

	// Register Dining Custom Post Type
	$labels = array(
		'name'                  => _x( 'Dinings', 'dinings', 'am' ),
		'singular_name'         => _x( 'Dining', 'dining', 'am' ),
		'menu_name'             => __( 'Dinings', 'am' ),
		'name_admin_bar'        => __( 'Dinings', 'am' ),
		'archives'              => __( 'Dinings Archives', 'am' ),
		'attributes'            => __( 'Dinings Attributes', 'am' ),
		'parent_item_colon'     => __( 'Parent Dinings:', 'am' ),
		'all_items'             => __( 'All Dinings', 'am' ),
		'add_new_item'          => __( 'Add Dining', 'am' ),
		'add_new'               => __( 'Add Dining', 'am' ),
		'new_item'              => __( 'New Dining', 'am' ),
		'edit_item'             => __( 'Edit Dining', 'am' ),
		'update_item'           => __( 'Update Dining', 'am' ),
		'view_item'             => __( 'View Dining', 'am' ),
		'view_items'            => __( 'View Dinings', 'am' ),
		'search_items'          => __( 'Search Dinings', 'am' ),
		'not_found'             => __( 'Not found', 'am' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'am' ),
		'featured_image'        => __( 'Featured Image', 'am' ),
		'set_featured_image'    => __( 'Set featured image', 'am' ),
		'remove_featured_image' => __( 'Remove featured image', 'am' ),
		'use_featured_image'    => __( 'Use as featured image', 'am' ),
		'insert_into_item'      => __( 'Insert into Dining', 'am' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Dining', 'am' ),
		'items_list'            => __( 'Dinings list', 'am' ),
		'items_list_navigation' => __( 'Dinings list navigation', 'am' ),
		'filter_items_list'     => __( 'Filter Dinings list', 'am' ),
	);
	$args   = array(
		'label'               => __( 'Dinings', 'am' ),
		'description'         => __( 'Dinings post type', 'am' ),
		'labels'              => $labels,
		'supports'            => array( 'title', 'custom-fields', 'page-attributes', 'thumbnail', 'excerpt', 'editor' ),
		'hierarchical'        => true,
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_rest'        => true,
		'menu_position'       => 5,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'can_export'          => true,
		'has_archive'         => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'capability_type'     => 'post',
		'rewrite'             => array(
			'with_front' => false,
			'slug'       => 'restaurants-bars',
		),
		'menu_icon'           => 'dashicons-food',
	);
	register_post_type( 'dining', $args );

	// Register Package Custom Post Type
	$labels = array(
		'name'                  => _x( 'Packages', 'packages', 'am' ),
		'singular_name'         => _x( 'Package', 'package', 'am' ),
		'menu_name'             => __( 'Packages', 'am' ),
		'name_admin_bar'        => __( 'Packages', 'am' ),
		'archives'              => __( 'Packages Archives', 'am' ),
		'attributes'            => __( 'Packages Attributes', 'am' ),
		'parent_item_colon'     => __( 'Parent Packages:', 'am' ),
		'all_items'             => __( 'All Packages', 'am' ),
		'add_new_item'          => __( 'Add Package', 'am' ),
		'add_new'               => __( 'Add Package', 'am' ),
		'new_item'              => __( 'New Package', 'am' ),
		'edit_item'             => __( 'Edit Package', 'am' ),
		'update_item'           => __( 'Update Package', 'am' ),
		'view_item'             => __( 'View Package', 'am' ),
		'view_items'            => __( 'View Packages', 'am' ),
		'search_items'          => __( 'Search Packages', 'am' ),
		'not_found'             => __( 'Not found', 'am' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'am' ),
		'featured_image'        => __( 'Featured Image', 'am' ),
		'set_featured_image'    => __( 'Set featured image', 'am' ),
		'remove_featured_image' => __( 'Remove featured image', 'am' ),
		'use_featured_image'    => __( 'Use as featured image', 'am' ),
		'insert_into_item'      => __( 'Insert into Package', 'am' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Package', 'am' ),
		'items_list'            => __( 'Packages list', 'am' ),
		'items_list_navigation' => __( 'Packages list navigation', 'am' ),
		'filter_items_list'     => __( 'Filter Packages list', 'am' ),
	);
	$args   = array(
		'label'               => __( 'Packages', 'am' ),
		'description'         => __( 'Packages post type', 'am' ),
		'labels'              => $labels,
		'supports'            => array( 'title', 'custom-fields', 'page-attributes', 'thumbnail', 'excerpt', 'editor' ),
		'hierarchical'        => true,
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_rest'        => true,
		'menu_position'       => 5,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'can_export'          => true,
		'has_archive'         => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'capability_type'     => 'post',
		'rewrite'             => array(
			'with_front' => false,
			'slug'       => 'packages',
		),
		'menu_icon'           => 'dashicons-buddicons-groups',
	);
	register_post_type( 'package', $args );

	// Register Event Custom Post Type
	// $labels = array(
	// 	'name'                  => _x( 'Events', 'events', 'am' ),
	// 	'singular_name'         => _x( 'Event', 'event', 'am' ),
	// 	'menu_name'             => __( 'Events', 'am' ),
	// 	'name_admin_bar'        => __( 'Events', 'am' ),
	// 	'archives'              => __( 'Events Archives', 'am' ),
	// 	'attributes'            => __( 'Events Attributes', 'am' ),
	// 	'parent_item_colon'     => __( 'Parent Events:', 'am' ),
	// 	'all_items'             => __( 'All Events', 'am' ),
	// 	'add_new_item'          => __( 'Add Event', 'am' ),
	// 	'add_new'               => __( 'Add Event', 'am' ),
	// 	'new_item'              => __( 'New Event', 'am' ),
	// 	'edit_item'             => __( 'Edit Event', 'am' ),
	// 	'update_item'           => __( 'Update Event', 'am' ),
	// 	'view_item'             => __( 'View Event', 'am' ),
	// 	'view_items'            => __( 'View Events', 'am' ),
	// 	'search_items'          => __( 'Search Events', 'am' ),
	// 	'not_found'             => __( 'Not found', 'am' ),
	// 	'not_found_in_trash'    => __( 'Not found in Trash', 'am' ),
	// 	'featured_image'        => __( 'Featured Image', 'am' ),
	// 	'set_featured_image'    => __( 'Set featured image', 'am' ),
	// 	'remove_featured_image' => __( 'Remove featured image', 'am' ),
	// 	'use_featured_image'    => __( 'Use as featured image', 'am' ),
	// 	'insert_into_item'      => __( 'Insert into Event', 'am' ),
	// 	'uploaded_to_this_item' => __( 'Uploaded to this Event', 'am' ),
	// 	'items_list'            => __( 'Events list', 'am' ),
	// 	'items_list_navigation' => __( 'Events list navigation', 'am' ),
	// 	'filter_items_list'     => __( 'Filter Events list', 'am' ),
	// );
	// $args   = array(
	// 	'label'               => __( 'Events', 'am' ),
	// 	'description'         => __( 'Events post type', 'am' ),
	// 	'labels'              => $labels,
	// 	'supports'            => array( 'title', 'custom-fields', 'page-attributes', 'thumbnail', 'excerpt', 'editor' ),
	// 	'hierarchical'        => true,
	// 	'public'              => true,
	// 	'show_ui'             => true,
	// 	'show_in_menu'        => true,
	// 	'show_in_rest'        => true,
	// 	'menu_position'       => 5,
	// 	'show_in_admin_bar'   => true,
	// 	'show_in_nav_menus'   => true,
	// 	'can_export'          => true,
	// 	'has_archive'         => false,
	// 	'exclude_from_search' => false,
	// 	'publicly_queryable'  => true,
	// 	'capability_type'     => 'post',
	// 	'rewrite'             => array(
	// 		'with_front' => false,
	// 		'slug'       => 'events',
	// 	),
	// 	'menu_icon'           => 'dashicons-tickets',
	// );
	// register_post_type( 'event', $args );

	// Register Gallery Custom Post Type
	$labels = array(
		'name'                  => _x( 'Galleries', 'galleries', 'am' ),
		'singular_name'         => _x( 'Gallery', 'gallery', 'am' ),
		'menu_name'             => __( 'Galleries', 'am' ),
		'name_admin_bar'        => __( 'Galleries', 'am' ),
		'archives'              => __( 'Galleries Archives', 'am' ),
		'attributes'            => __( 'Galleries Attributes', 'am' ),
		'parent_item_colon'     => __( 'Parent Galleries:', 'am' ),
		'all_items'             => __( 'All Galleries', 'am' ),
		'add_new_item'          => __( 'Add Gallery', 'am' ),
		'add_new'               => __( 'Add Gallery', 'am' ),
		'new_item'              => __( 'New Gallery', 'am' ),
		'edit_item'             => __( 'Edit Gallery', 'am' ),
		'update_item'           => __( 'Update Gallery', 'am' ),
		'view_item'             => __( 'View Gallery', 'am' ),
		'view_items'            => __( 'View Galleries', 'am' ),
		'search_items'          => __( 'Search Galleries', 'am' ),
		'not_found'             => __( 'Not found', 'am' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'am' ),
		'featured_image'        => __( 'Featured Image', 'am' ),
		'set_featured_image'    => __( 'Set featured image', 'am' ),
		'remove_featured_image' => __( 'Remove featured image', 'am' ),
		'use_featured_image'    => __( 'Use as featured image', 'am' ),
		'insert_into_item'      => __( 'Insert into Gallery', 'am' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Gallery', 'am' ),
		'items_list'            => __( 'Galleries list', 'am' ),
		'items_list_navigation' => __( 'Galleries list navigation', 'am' ),
		'filter_items_list'     => __( 'Filter Galleries list', 'am' ),
	);
	$args   = array(
		'label'               => __( 'Galleries', 'am' ),
		'description'         => __( 'Galleries post type', 'am' ),
		'labels'              => $labels,
		'supports'            => array( 'title' ),
		'hierarchical'        => false,
		'public'              => false,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_rest'        => true,
		'menu_position'       => 5,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'can_export'          => true,
		'has_archive'         => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'capability_type'     => 'post',
		'menu_icon'           => 'dashicons-format-gallery',
	);
	register_post_type( 'gallery', $args );

	
	// Register Location Custom Post Type
	$labels = array(
		'name'                  => _x( 'Locations', 'locations', 'am' ),
		'singular_name'         => _x( 'Location', 'location', 'am' ),
		'menu_name'             => __( 'Locations', 'am' ),
		'name_admin_bar'        => __( 'Locations', 'am' ),
		'archives'              => __( 'Locations Archives', 'am' ),
		'attributes'            => __( 'Locations Attributes', 'am' ),
		'parent_item_colon'     => __( 'Parent Locations:', 'am' ),
		'all_items'             => __( 'All Locations', 'am' ),
		'add_new_item'          => __( 'Add Location', 'am' ),
		'add_new'               => __( 'Add Location', 'am' ),
		'new_item'              => __( 'New Location', 'am' ),
		'edit_item'             => __( 'Edit Location', 'am' ),
		'update_item'           => __( 'Update Location', 'am' ),
		'view_item'             => __( 'View Location', 'am' ),
		'view_items'            => __( 'View Locations', 'am' ),
		'search_items'          => __( 'Search Locations', 'am' ),
		'not_found'             => __( 'Not found', 'am' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'am' ),
		'featured_image'        => __( 'Featured Image', 'am' ),
		'set_featured_image'    => __( 'Set featured image', 'am' ),
		'remove_featured_image' => __( 'Remove featured image', 'am' ),
		'use_featured_image'    => __( 'Use as featured image', 'am' ),
		'insert_into_item'      => __( 'Insert into Gallery', 'am' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Gallery', 'am' ),
		'items_list'            => __( 'Locations list', 'am' ),
		'items_list_navigation' => __( 'Locations list navigation', 'am' ),
		'filter_items_list'     => __( 'Filter Locations list', 'am' ),
	);
	$args   = array(
		'label'               => __( 'Locations', 'am' ),
		'description'         => __( 'Locations post type', 'am' ),
		'labels'              => $labels,
		'supports'            => array( 'title', 'thumbnail', 'editor', 'excerpt' ),
		'hierarchical'        => false,
		'public'              => false,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_rest'        => true,
		'menu_position'       => 5,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'can_export'          => true,
		'has_archive'         => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'capability_type'     => 'post',
		'menu_icon'           => 'dashicons-location',
	);
	register_post_type( 'location', $args );
}
